alias: EZHI stable output - Timed check
description: ''
triggers:
  - trigger: time_pattern
    minutes: /1
conditions:
  - condition: state
    entity_id: input_select.ezhi_mode
    state:
      - Stable output (auto)
      - Stable output (permanent)
  - condition: template
    value_template: >
      {{ is_number(states('number.ezhi_apsystems_ezhi_on_grid_power'))
         and states('number.ezhi_apsystems_ezhi_on_grid_power') | float != 40 }}
actions:
  - action: number.set_value
    metadata: {}
    target:
      entity_id: number.ezhi_apsystems_ezhi_on_grid_power
    data:
      value: '40'
mode: single
